services:
  redis:
    image: bitnami/redis:latest
    container_name: redis-evet-manage-tjk
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

volumes:
  pgdata:
  redis_data:
